name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          # key: ${{ secrets.REMOTE_SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd PetProject
            docker exec -t -e PGPASSWORD=postgres  db pg_dump -U maintainer -d postgres -p 6101 > dump_pokerbot.sql
            docker-compose down
            cd ..
            rm -rf PetProject
            git clone git@github.com:Ignntbc/PetProject.git
            cd PetProject
            docker-compose build
            docker-compose up -d
            sleep 10
            type dump_pokerbot.sql |docker exec -i db psql -U maintainer -d postgres -p 6101 
            goose -dir migrations postgres "postgresql://maintainer:postgres@185.233.186.104:6101/postgres?sslmode=disable" up

            