name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Build and push container
      #   run: |
      #     docker build -t petproject-bot .
      #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      #     docker tag petproject-bot igntbc/petproject-bot
      #     docker push igntbc/petproject-bot

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          # key: ${{ secrets.REMOTE_SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            screen -x PetProject
            cd PetProject
            docker-compose down
            cd ..
            rm -rf PetProject
            git clone git@github.com:Ignntbc/PetProject.git
            cd PetProject
            docker-compose build
            docker-compose up
            goose -dir migrations up
            screen -d
            